name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image http-server-trace
      run: docker build . --file http-server-trace/Dockerfile --tag docker-to-the-security:http-server-trace
